# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and test with Docker
      run: |
        mkdir -p output.png
        chmod 777 output.png
        docker build --build-arg USER_ID=$(id -u) -t google-calc .
        docker run -u $(id -u) -v output.png:/home/uchrome/google_calc/output.png google-calc pytest -v --driver=Chrome --headless --session
    - name: Upload no session result
      uses: actions/upload-artifact@v2
      with:
        name: no_session_output
        path: output.png/*.*
